[project]
name = "tensorzero-recipes-mipro"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "clickhouse-connect",
    "exceptiongroup",
    "ipykernel",
    "minijinja",
    "openai",
    "optuna",
    "pandas",
    "pydantic",
    "seaborn",
    "tensorzero",
    "toml",
    "tqdm",
]

[tool.uv]
constraint-dependencies = ["fonttools>=4.60.2", "urllib3>=2.6.0"]
