[package]
name = "tensorzero-types"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aws-smithy-types = { version = "1.4.0", features = ["byte-stream-poll-next"] }
infer.workspace = true
mime.workspace = true
object_store.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
tensorzero-derive = { path = "../tensorzero-derive" }
thiserror.workspace = true
tracing.workspace = true
ts-rs = { workspace = true, optional = true }
url = { workspace = true, features = ["serde"] }

[features]
default = []
pyo3 = ["dep:pyo3"]
e2e_tests = []
ts-bindings = ["dep:ts-rs"]

[dependencies.pyo3]
workspace = true
optional = true

[lints]
workspace = true
