version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
    open-pull-requests-limit: 0 # only send security updates

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
    open-pull-requests-limit: 0 # only send security updates

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
    open-pull-requests-limit: 0 # only send security updates
    # These paths contain educational content that is not directly meant for production use.
    # Automatic upgrades are likely to break them over time as they're not actively tested.
    exclude-paths:
      - "examples/**"
      - "recipes/**"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # This schedule does not affect security updates: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/customizing-dependabot-security-prs#about-customizing-pull-requests-for-security-updates
      interval: "weekly"
    labels: []
    groups:
      opentelemetry-dependencies:
        patterns:
          - "*opentelemetry*"
          - "tonic"
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 2 # This does not affect the security update PR limit
