[project]
name = "tensorzero-recipes"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "clickhouse-connect",
    "pandas",
    "pydantic",
    "tensorzero",
    "tiktoken",
    "toml",
]

[tool.uv.workspace]
members = ["tensorzero-recipes"]

[dependency-groups]
dev = [
    "pandas-stubs",
    "pyright",
    "pytest-asyncio",
    "pytest",
]

[tool.uv]
constraint-dependencies = ["urllib3>=2.6.0"]
