[package]
name = "autopilot-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
durable-tools = { path = "../durable-tools" }

[lints]
workspace = true
