# cargo-deny

[bans]
deny = [
    { name = "native-tls" },
    { name = "openssl" },
    { name = "openssl-sys"}
]

[advisories]
ignore = [
    "RUSTSEC-2024-0436" # We don't care that 'paste' is unmaintained
]
