# cargo-deny

[bans]
deny = [
    { name = "native-tls" },
    { name = "openssl" },
    { name = "openssl-sys"}
]

[advisories]
ignore = [
    "RUSTSEC-2024-0436" # We don't care that 'paste' is unmaintained
]

[licenses]
version = 2
allow = ["Unicode-3.0", "Apache-2.0", "MIT", "CDLA-Permissive-2.0", "ISC", "CC0-1.0", "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "Zlib", "MIT-0", "OpenSSL", "BSD-2-Clause"]
