services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP port
      - "9000:9000"  # Native port
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  api:
    command: ["api", "/app/tensorzero.test.toml"]
    environment:
      - CLICKHOUSE_URL=http://clickhouse:8123
    volumes:
      - ./tensorzero.test.toml:/app/tensorzero.test.toml


volumes:
  clickhouse-data:
