# You can use this configuration file to define custom functions, models, and more.
# This is useful for using advanced TensorZero features with Codex.
#
# See our https://www.tensorzero.com/docs/quickstart/ for more details.

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

# You can use this function on Codex with `tensorzero::function_name::codex`.
[functions.codex]
type = "chat"

[functions.codex.variants.anthropic_claude_4_5_sonnet]
type = "chat_completion"
model = "anthropic::claude-sonnet-4-5"
retries = { num_retries = 4, max_delay_s = 10 }
