[package]
name = "tensorzero-derive"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
description = "Macros for TensorZero"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.114", features = ["full"] }

[lints]
workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
trybuild = "1.0.114"
