[package]
name = "tensorzero-derive"
version = "0.1.0"
rust-version.workspace = true
edition = "2021"
license.workspace = true
description = "Macros for TensorZero"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.109", features = ["full"] }

[lints]
workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
trybuild = "1.0.114"
