services:
  gateway:
    container_name: tensorzero-gateway
    image: tensorzero/gateway
    volumes:
      - ./config:/app/config:ro
      - ${GCP_VERTEX_CREDENTIALS_PATH:-/dev/null}:/app/gcp-credentials.json:ro
    environment:
      - GCP_VERTEX_CREDENTIALS_PATH=${GCP_VERTEX_CREDENTIALS_PATH:+/app/gcp-credentials.json}
      - TENSORZERO_CLICKHOUSE_URL=${TENSORZERO_CLICKHOUSE_URL}
      - CLICKHOUSE_URL=${CLICKHOUSE_URL} # Deprecated, but still supported
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: wget --spider --tries 1 http://localhost:3000/status || exit 1
      interval: 15s
      timeout: 1s
      retries: 2
