[project]
name = "tensorzero-recipes-supervised-fine-tuning-metrics-fireworks"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "clickhouse-connect",
    "ipykernel",
    "notebook",
    "numpy",
    "tensorzero",
    "toml",
    "dotenv"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
