[models."openai/gpt-oss-20b"]
routing = ["hyperbolic"]

[models."openai/gpt-oss-20b".providers.hyperbolic]
type = "hyperbolic"
model_name = "openai/gpt-oss-20b"

[functions.my_function_name]
type = "chat"

[functions.my_function_name.variants.my_variant_name]
type = "chat_completion"
model = "openai/gpt-oss-20b"
