# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.cursorzero]
type = "chat"

[functions.cursorzero.variants."gpt-4.1"]
weight = 1
type = "chat_completion"
model = "openai::gpt-4.1"

[functions.cursorzero.variants."claude-3.7"]
weight = 1
type = "chat_completion"
model = "anthropic::claude-3-7-sonnet-20250219"

[functions.cursorzero.variants."gemini-2.5-pro"]
weight = 1
type = "chat_completion"
model = "google_ai_studio_gemini::gemini-2.5-pro"

[functions.cursorzero.variants."o4-mini"]
weight = 1
type = "chat_completion"
model = "openai::o4-mini-2025-04-16"
extra_body = [{ pointer = "/temperature", value = 1.0 }]

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  METRICS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[metrics.average_ted_ratio]
type = "float"
level = "inference"
optimize = "min"

# this is just to observe, probably not to optimize
[metrics.num_code_blocks]
type = "float"
level = "inference"
optimize = "max"

# As a measurement of how much code was output
[metrics.total_tree_size]
type = "float"
level = "inference"
optimize = "max"
