# NOTE: This is an example configuration file for TensorZero.
#       You can use this file as a reference for your own configuration by adding
#       your own models, functions, and metrics.

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  GENERAL                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[gateway]
bind_address = "0.0.0.0:3000"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                   MODELS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[models."gpt-3.5-turbo"]
routing = ["openai", "azure"]

[models."gpt-3.5-turbo".providers.openai]
type = "openai"
model_name = "gpt-3.5-turbo"

[models."gpt-3.5-turbo".providers.azure]
type = "azure"
deployment_id = "gpt-35-turbo"
endpoint = "https://your-endpoint.openai.azure.com"

[models.claude-3-haiku-20240307]
routing = ["anthropic"]

[models.claude-3-haiku-20240307.providers.anthropic]
type = "anthropic"
model_name = "claude-3-haiku-20240307"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.generate-draft]
type = "chat"
system_schema = "functions/example_generate_draft/system_schema.json"

[functions.generate-draft.variants.openai-promptA]
type = "chat_completion"
weight = 0.9
model = "gpt-3.5-turbo"
system_template = "functions/example_generate_draft/promptA/system_template.minijinja"

[functions.generate-draft.variants.openai-promptB]
type = "chat_completion"
weight = 0.1
model = "gpt-3.5-turbo"
system_template = "functions/example_generate_draft/promptB/system_template.minijinja"

[functions.extract-data]
type = "json"
system_schema = "functions/example_extract_data/system_schema.json"
output_schema = "functions/example_extract_data/output_schema.json"

[functions.extract-data.variants.openai-promptA]
type = "chat_completion"
weight = 0.9
model = "gpt-3.5-turbo"
system_template = "functions/example_extract_data/promptA/system_template.minijinja"

[functions.extract-data.variants.openai-promptB]
type = "chat_completion"
weight = 0.1
model = "gpt-3.5-turbo"
system_template = "functions/example_extract_data/promptB/system_template.minijinja"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  METRICS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[metrics.task-success]
type = "boolean"    # "boolean", "float"
optimize = "max"    # "min", "max"
level = "inference" # "inference", "episode"

[metrics.user-rating]
type = "float"
optimize = "max"
level = "episode"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  TOOLS                                     │
# └────────────────────────────────────────────────────────────────────────────┘

[tools.query-articles]
description = "Query articles from Wikipedia"
parameters = "tools/example_query_articles.json"
