[project]
name = "tensorzero-recipes-supervised-fine-tuning-demonstrations-fireworks"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "clickhouse-connect",
    "ipykernel",
    "minijinja",
    "notebook",
    "pandas",
    "tensorzero",
    "toml",
    "dotenv"
]
