[package]
name = "tensorzero-node"
version.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = [
    "napi4",
    "tokio_rt",
] }
napi-derive = "2.12.2"
serde_json.workspace = true
secrecy.workspace = true
tensorzero-core = { path = "../../tensorzero-core" }
tensorzero-auth = { path = "../../internal/tensorzero-auth" }

[build-dependencies]
napi-build = "2.3.0"
