[project]
name = "tensorzero-recipes-supervised-fine-tuning-metrics-together"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel",
    "notebook",
    "numpy",
    "requests",
    "tensorzero",
    "toml",
    "together",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
