[project]
name = "tensorzero-examples-docs-guides-optimization-dynamic-in-context-learning-dicl"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.6.1",
    "pandas>=2.3.3",
    "tensorzero>=2025.12.3",
    "tqdm>=4.66.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.0",
]
