[package]
name = "minijinja-utils"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
minijinja.workspace = true
serde = { workspace = true, features = ["derive"] }
tracing.workspace = true

[lints]
workspace = true
