[project]
name = "require-tensorzero-api-keys-auth"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=2.6.1",
    "pandas>=2.3.3",
    "tensorzero>=2025.11.0",
    "tqdm>=4.66.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.0",
]

[tool.uv.sources]
tensorzero = { path = "../../../../../clients/python" }  # TODO: DO NOT MERGE
