[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "tensorzero"
license = "Apache-2.0"
requires-python = ">=3.9"
dependencies = ["httpx>=0.27.0", "uuid-utils>=0.9.0"]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
strip = true
