[models.claude_haiku_4_5_20251001]
routing = ["anthropic"]

[models.claude_haiku_4_5_20251001.providers.anthropic]
type = "anthropic"
model_name = "claude-haiku-4-5-20251001"

[functions.my_function_name]
type = "chat"

[functions.my_function_name.variants.my_variant_name]
type = "chat_completion"
model = "claude_haiku_4_5_20251001"
