[models.claude_3_5_haiku_20241022]
routing = ["anthropic"]

[models.claude_3_5_haiku_20241022.providers.anthropic]
type = "anthropic"
model_name = "claude-3-5-haiku-20241022"

[functions.my_function_name]
type = "chat"

[functions.my_function_name.variants.my_variant_name]
type = "chat_completion"
model = "claude_3_5_haiku_20241022"
