name: Build Gateway Container

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_LIMITED_TOKEN:
        required: true

env:
  TAG: tensorzero/gateway-e2e:sha-${{ github.sha }}
  LATEST_TAG: tensorzero/gateway-e2e:latest
  TENSORZERO_COMMIT_TAG: sha-${{ github.sha }}

jobs:
  build-gateway-container:
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero'
    permissions:
      # Permission to checkout the repository
      contents: read
      # Permission to fetch GitHub OIDC token authentication
      id-token: write

    steps:
      # TODO - investigate why using the Namespace checkout action causes
      # 'tensorzero_core::built_info::GIT_COMMIT_HASH_SHORT' to be `None`
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # We use 'DOCKERHUB_LIMITED_TOKEN' to ensure that we can only push to our private '-dev' repos,
      # not to any of the public production repos.
      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          # We're using an organization access token, so we need to use the org name for the username.
          username: tensorzero
          password: ${{ secrets.DOCKERHUB_LIMITED_TOKEN }}

      # We allow the namespace builder setup to fail on Dependabot PRs and PRs from forks
      # (where the oidc token is not available)

      - name: Install Namespace CLI
        uses: namespacelabs/nscloud-setup@d1c625762f7c926a54bd39252efff0705fd11c64
        continue-on-error: ${{ github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]' }}

      - name: Configure Namespace-powered Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@91c2e6537780e3b092cb8476406be99a8f91bd5e
        with:
          wait-for-builder: true
        continue-on-error: ${{ github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]' }}

      - name: Build test containers
        run: docker compose -f tensorzero-core/tests/e2e/docker-compose.live.yml --profile provider-proxy build provider-proxy gateway live-tests

      - name: Save test containers
        run: |
          docker save tensorzero/provider-proxy:sha-${{ github.sha }} > provider-proxy-container.tar
          docker save tensorzero/gateway-e2e:sha-${{ github.sha }} > gateway-e2e-container.tar
          docker save tensorzero/live-tests:sha-${{ github.sha }} > live-tests-container.tar

      - name: Upload provider-proxy container as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: build-provider-proxy-container
          path: provider-proxy-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      - name: Upload gateway-e2e container as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: build-gateway-e2e-container
          path: gateway-e2e-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      - name: Upload live-tests container as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: build-live-tests-container
          path: live-tests-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      # Note that this pushes an e2e build of the gateway to 'tensorzero/gateway-e2e'.
      # It does *not* push to the production 'tensorzero/gateway' repo.
      - name: Push test containers
        run: docker compose -f tensorzero-core/tests/e2e/docker-compose.live.yml --profile provider-proxy push provider-proxy gateway live-tests
