name: Build Live Tests Container

on:
  workflow_call:
    inputs:
      distribution_mode:
        description: "How to distribute built images: `artifact` or `registry`"
        required: false
        type: string
        default: artifact
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_LIMITED_TOKEN:
        required: false

jobs:
  build-live-tests-container:
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero'
    permissions:
      # Permission to checkout the repository
      contents: read
      # Permission to fetch GitHub OIDC token authentication
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # We allow the namespace builder setup to fail on Dependabot PRs and PRs from forks
      # (where the GitHub OIDC token is not available)

      - name: Install Namespace CLI
        if: inputs.distribution_mode == 'registry'
        uses: namespacelabs/nscloud-setup@d1c625762f7c926a54bd39252efff0705fd11c64

      - name: Configure Namespace-powered Buildx
        if: inputs.distribution_mode == 'registry'
        uses: namespacelabs/nscloud-setup-buildx-action@91c2e6537780e3b092cb8476406be99a8f91bd5e
        with:
          wait-for-builder: true

      - name: Build `live-tests` container
        run: |
          TAGS="-t tensorzero/live-tests:sha-${{ github.sha }}"
          if [ "${{ inputs.distribution_mode }}" = "registry" ]; then
            TAGS="$TAGS -t nscr.io/igvf4asmf8kri/live-tests:sha-${{ github.sha }}"
          fi
          docker buildx build --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 -f tensorzero-core/tests/e2e/Dockerfile.live . ${TAGS}

      - name: Save `live-tests` container
        if: inputs.distribution_mode == 'artifact'
        run: docker save tensorzero/live-tests:sha-${{ github.sha }} > live-tests-container.tar

      - name: Upload `live-tests` container as an artifact
        if: inputs.distribution_mode == 'artifact'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: build-live-tests-container
          path: live-tests-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      - name: Login to Namespace registry
        if: inputs.distribution_mode == 'registry'
        run: nsc docker login

      - name: Push `live-tests` container to Namespace registry
        if: inputs.distribution_mode == 'registry'
        run: docker push nscr.io/igvf4asmf8kri/live-tests:sha-${{ github.sha }}
