name: Build UI Container

on:
  workflow_call:
    inputs:
      distribution_mode:
        description: "How to distribute built images: `artifact` or `registry`"
        required: false
        type: string
        default: artifact

jobs:
  build-ui-container:
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero'
    permissions:
      # Permission to checkout the repository
      contents: read
      # Permission to fetch GitHub OIDC token authentication
      id-token: write

    steps:
      # TODO - investigate why using the Namespace checkout action causes
      # 'tensorzero_core::built_info::GIT_COMMIT_HASH_SHORT' to be `None`
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # We allow the namespace builder setup to fail on Dependabot PRs and PRs from forks
      # (where the oidc token is not available)

      - name: Install Namespace CLI
        if: inputs.distribution_mode == 'registry'
        uses: namespacelabs/nscloud-setup@d1c625762f7c926a54bd39252efff0705fd11c64

      - name: Configure Namespace-powered Buildx
        if: inputs.distribution_mode == 'registry'
        uses: namespacelabs/nscloud-setup-buildx-action@91c2e6537780e3b092cb8476406be99a8f91bd5e
        with:
          wait-for-builder: true

      - name: Build `ui` container
        run: |
          TAGS="-t tensorzero/ui:sha-${{ github.sha }}"
          if [ "${{ inputs.distribution_mode }}" = "registry" ]; then
            TAGS="$TAGS -t nscr.io/igvf4asmf8kri/ui:sha-${{ github.sha }}"
          fi
          docker buildx build --build-arg DEBUG_BUILD=1 --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 -f ui/Dockerfile . ${TAGS}

      - name: Save `ui` container
        if: inputs.distribution_mode == 'artifact'
        run: docker save tensorzero/ui:sha-${{ github.sha }} > ui-container.tar

      - name: Upload `ui` container as an artifact
        if: inputs.distribution_mode == 'artifact'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: build-ui-container
          path: ui-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      - name: Login to Namespace registry
        if: inputs.distribution_mode == 'registry'
        run: nsc docker login

      - name: Push `ui` container to Namespace registry
        if: inputs.distribution_mode == 'registry'
        run: docker push nscr.io/igvf4asmf8kri/ui:sha-${{ github.sha }}
