name: Build UI Container

on:
  workflow_call:

jobs:
  build-ui-container:
    runs-on: namespace-profile-tensorzero-8x16;overrides.cache-tag=build-ui-cache

    steps:
      - uses: namespacelabs/nscloud-checkout-action@953fed31a6113cc2347ca69c9d823743c65bc84b

      - name: Build `ui` container
        run: |
          docker build --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 -f ui/Dockerfile . -t tensorzero/ui:sha-${{ github.sha }}

      - name: Save `ui` container
        run: docker save tensorzero/ui:sha-${{ github.sha }} > ui-container.tar

      - name: Upload `ui` container as an artifact to Namespace
        uses: namespace-actions/upload-artifact@9a78c62e083914789d908952f9773e42744b9f68
        with:
          name: build-ui-container
          path: ui-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false

      - name: Upload `ui` container as an artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: build-ui-container
          path: ui-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false
