name: Build

on:
  workflow_call:

jobs:
  gateway:
    runs-on: namespace-profile-tensorzero-8x16

    steps:
      - uses: namespacelabs/nscloud-checkout-action@953fed31a6113cc2347ca69c9d823743c65bc84b

      - name: Build `gateway` container
        run: |
          docker build -f gateway/Dockerfile . -t tensorzero/gateway

      - name: Save `gateway` container
        run: docker save tensorzero/gateway > gateway-container.tar

      - name: Upload `gateway` container as an artifact
        uses: namespace-actions/upload-artifact@9a78c62e083914789d908952f9773e42744b9f68
        with:
          name: build
          path: gateway-container.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: false
