name: Build UI Dev Container

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to check out and tag. Falls back to github.sha if not provided."
        required: false
        type: string
        default: ""
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_LIMITED_TOKEN:
        required: true

jobs:
  build-ui-dev-container:
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero'
    permissions:
      # Permission to checkout the repository
      contents: read
      # Permission to fetch GitHub OIDC token authentication
      id-token: write
    env:
      EFFECTIVE_REF: ${{ inputs.ref || github.sha }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.ref || github.sha }}

      # We use 'DOCKERHUB_LIMITED_TOKEN' to ensure that we can only push to our private '-dev' repos,
      # not to any of the public production repos.
      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: tensorzero
          password: ${{ secrets.DOCKERHUB_LIMITED_TOKEN }}

      - name: Install Namespace CLI
        uses: namespacelabs/nscloud-setup@d1c625762f7c926a54bd39252efff0705fd11c64
        continue-on-error: ${{ github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]' }}

      - name: Configure Namespace-powered Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@91c2e6537780e3b092cb8476406be99a8f91bd5e
        with:
          wait-for-builder: true
        continue-on-error: ${{ github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]' }}

      - name: Build `ui-dev` container
        run: |
          docker buildx build --build-arg DEBUG_BUILD=1 --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 -f ui/Dockerfile . -t tensorzero/ui-dev:sha-${{ env.EFFECTIVE_REF }}

      - name: Push `ui-dev` container to DockerHub
        run: docker push tensorzero/ui-dev:sha-${{ env.EFFECTIVE_REF }}
