name: PR Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  # We don't want to run live-tests on PRs, so we use a dummy job to satisfy branch protection checks
  live-tests:
    runs-on:
      - namespace-profile-tensorzero-2x8
      - nscloud-cache-exp-do-not-commit

    timeout-minutes: 5

    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
