on:
  push:
    branches: ["aaron/wrap-general"]

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  general:
    uses: ./.github/workflows/general.yml
    permissions:
      contents: read
      actions: write
      id-token: write
    secrets: inherit

  post-general:
    runs-on: ubuntu-latest
    needs: [general]
    steps:
      - name: Post general
        run: |
          echo "Post general"