[package]
name = "tensorzero-auth"
edition = "2024"
version.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hex = "0.4.3"
secrecy.workspace = true
serde.workspace = true
sha2 = "0.10.9"
# Unfortunately, this cannot be a workspace dependency, since renaming the 'sqlx' package breaks all of the macros
# (which emit '::sqlx' tokens)
sqlx = { version = "0.9.0-alpha.1", features = ["sqlx-toml", "postgres", "runtime-tokio", "chrono", "tls-rustls"] }
thiserror = "2.0.17"
rand = { workspace = true }
chrono.workspace = true
futures = { workspace = true }
ts-rs.workspace = true

[lints]
workspace = true

[[test]]
name = "e2e"
path = "tests/e2e/tests.rs"
required-features = ["e2e_tests"]

[features]
e2e_tests = []
